# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:06
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=32)),
                ('leave_part', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=4)),
                ('date', models.DateField()),
                ('approval_status', models.BooleanField(default=False)),
                ('approved_statuschange_on', models.DateField(default=datetime.datetime.today)),
                ('reason', models.CharField(default='', max_length=256)),
                ('approved_statuschange_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuschangeby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('joiningdate', models.DateField(default=datetime.date(2015, 1, 1))),
                ('department', models.CharField(default='IT', max_length=140)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
