# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval_status',
            field=models.CharField(default='pending', max_length=32),
        ),
    ]
