# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160427_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(default='', max_length=10),
        ),
    ]
