# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
