# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160427_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('falling_on', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
